version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
  backend:
    build: ./backend
    ports:
      - '3001:3001'
    environment:
      - DATABASE_URL=postgres://user:pass@db:5432/rehearsal
  db:
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=rehearsal
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
